SEED_NUMBER = 11
NUMBER_OF_FOLDS = 1
NO_EXPERIMENTS_AVERAGING = 1
DO_AVERAGING = False


DATA_HEADER = "emotions"
NO_ATTRIBUTES = 72
VALID_DATA_HEADER = DATA_HEADER + "-test"
TRAIN_DATA_HEADER = DATA_HEADER + "-train"
DATA_FOLDER = "C:\Datasets"
RUN_RESULT_PATH = "Run_results_MLRBC"


NO_TRAIN_ITERATION = 1000
POP_SIZE = 1000
NO_PARALLEL_JOBS = 1
DISTRIBUTED_MATCHING_TH = 6000
PREDICTION_METHOD = 'max'



