SEED_NUMBER = 11
NUMBER_OF_FOLDS = 1
NO_EXPERIMENTS_AVERAGING = 1
DO_AVERAGING = True


DATA_HEADER = "data1"
NO_ATTRIBUTES = 2
VALID_DATA_HEADER = DATA_HEADER + "-test"
TRAIN_DATA_HEADER = DATA_HEADER + "-train"
DATA_FOLDER = "C:\Datasets\synthetic"
RUN_RESULT_PATH = "Run_results_MLRBC"


NO_TRAIN_ITERATION = 150000
POP_SIZE = 400
NO_PARALLEL_JOBS = 1
DISTRIBUTED_MATCHING_TH = 6000
PREDICTION_METHOD = 'max'
ADAPT_THETA_GA = False
PLOT_SETTING = [0, 1, 1, 0]   # population sizes, accuracy, Hloss, generality


